# Generated by Django 5.1.3 on 2024-11-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                related_name="posts", to="blog.category", verbose_name="Categorías"
            ),
        ),
    ]
