name: Django CI

on:
  push:
    branches: [ "main" ]  # Ejecutar cuando haya cambios en la rama principal
  pull_request:
    branches: [ "main" ]  # Ejecutar cuando se cree un PR para la rama principal

jobs:
  build_and_test:
    runs-on: ubuntu-latest  # Usar Ubuntu para ejecutar el flujo de trabajo

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Clona el código del repositorio

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Usar Python 3.12.6

    - name: Show Python and Pip Versions
      run: |
        python --version  # Muestra la versión activa de Python
        pip --version     # Muestra la versión activa de pip

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip  # Actualiza pip a la última versión
        pip install -r requirements.txt      # Instala dependencias desde requirements.txt

    - name: Run Tests
      run: |
        cd webpersonal  # Cambia a la carpeta de tu proyecto Django
        python manage.py test  # Ejecuta los tests definidos en tu proyecto